### ISSUE TITLE
Virtual resource

### ISSUE THREAD

**Issue by cvsup** [xaque208/puppet-bacula#101]
When run puppet agent -t in node this report the follow error:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Failed to realize virtual resources Package[bacula-director-mysql] on node
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Manifest configuration

        class { 'bacula':
                director_name   => 'shelenagw-dir',
        }

        class { 'bacula::director':
                #packages       => ['bacula-director', 'bacula-common', 'bacula-sd'],
                password        => 'test123',
                db_type         => 'mysql',
                manage_db       => false,
                db_name         => 'bacula',
                db_user         => 'bacula',
                db_pw           => 'bacula',
        }

**Comment by xaque208** [comment]
thanks for the note.  This is related to #58.  Currently there is not code in place to handle mysql.  If you are in a position to use postgres in place of mysql, that would likely be the fastest path forward.  Also, if you are able to help add support for mysql to this module, it should be only a few resources that look similar to the postgres code that is in place currently.

**Comment by xaque208** [comment]
Hi @cvsup Are you able to help with this work?  Is this still a requirement for you?

**Comment by smortex** [comment]
I think that this issue has been overcome by events.  As of f9548141e2bd290c138db36ed2f4fb588d2589b3 we do not use virtual resources to install packages anymore.

The fact that MySQL is not supported still exist but #58 is already there :wink:.

Maybe we can close this issue?

**Comment by xaque208** [comment]
Seems reasonable to me.
