### ISSUE TITLE
Bacula::Director::Client[$HOST]: has no parameter named 'address'

### ISSUE THREAD

**Issue by jflorian** [xaque208/puppet-bacula#104]
I started trying to update to 5.1.1 and now 5.2.0 and both have led me to this error.  I followed the upgrade notes (and will have a few README updates via a PR soon).  Any idea why I'm getting this error that only seems to occur on the host that serves as both my Director and Storage?

**Comment by jflorian** [comment]
FWIW, my Director/Storage host is running puppet-4.2.1-5.fc25.noarch.  I have tried putting the following in my common hiera.yaml:

    bacula::client::address:    "%{fqdn}"

Unfortunately, that didn't help either.  (I did run puppet again on eacho value of $HOST that I see in the error *prior* to trying the run on the Director/Storage host.)

**Comment by xaque208** [comment]
Hi!  Without looking at the code, I suspect that there is a client that has not run the new code, so the exported resource contains an invalid param when the director goes to realize the resource.  So for the upgrade, I think all nodes will need to run the new code before the director will compile.  Does that match your experience?  I can dig in code if I'm off the map.

**Comment by jflorian** [comment]
I was kind of wondering about that.  I was running the new code for each host mentioned in the error message figuring  that would clean up the exported resources causing that specific error.  However, it may be that the error is misleading.  It wouldn't be the first time I've seen Puppet do that to me.

I will run the new code against all nodes to see if that makes the problem go away.  I had almost considered it before and your suspicion only affirms my own.  I'll let ya know what I learn.

**Comment by jflorian** [comment]
Well, it looks like that was exactly the issue.  I was trying to do an incremental roll out to test this and that's exactly what burned me.  I'd submit another quick patch to the readme to mention this but I'm completely fried this week pushing an embedded OS upgrade to over 500 devices.  Plus, it might be unique to my environment.  For example, I had to make the following change that gets applied to all of my bacula clients:
```diff
-        ::bacula::fileset { $::hostname:
+        @@::bacula::director::fileset { $::hostname:
```

The important bit to notice is not the define rename but that I must now export this.  It seems like it should have been required before, but perhaps that's just me forgetting what the readme already mentioned per the upgrade requirements.  Did I mention that I'm fried?

**Comment by xaque208** [comment]
I'll close this issue out, but I'm open to review how you're using the module.  I don't have access to my personal use of this at the moment, but I don't think I'm exporting any of the filesets.  Rather, I think I'm including them only on the master in a single class, then referencing them on the backup jobs for each of the nodes.  So I have perhaps 10 or so filesets centrally defined, but perhaps 20 nodes in all.  I also have multiple jobs per host, which is a bit more topical than 'everything on this host' sort of backups.

I'd welcome another readme PR when you are more rested. :)  Also, thanks for upgrading!
