### ISSUE TITLE
Consider a new forge.puppet.com release

### ISSUE THREAD

**Issue by phaer** [xaque208/puppet-bacula#108]
Hi,

Thanks for your work on `puppet-bacula`, I noticed that the badge at the beginning of README.md as well as metadata.json refer to https://forge.puppet.com/zleslie/bacula/ which is still on version 4.0.0 while the latest release in this git repository is 5.2.0. Is there a reason for this? Would it be possible to push a new release to puppet forge or is there anything blocking this?

**Comment by xaque208** [comment]
Thanks for the reminder.  No blockers, I just don't use the forge much.  The version on the forge has been bumped as requested.  I'm sure I'll forget again.  If you need older versions for whatever reason, just let me know and I'll put them up.
