### ISSUE TITLE
New client wont' start; doesn't have TLS directory or certificates

### ISSUE THREAD

**Issue by jflorian** [xaque208/puppet-bacula#131]
I've added a new host to my collection and the Bacula client won't start because the FD cannot find the TLS certs that it's been told to use.  On my hosts, these have wound up in `/etc/bacula/ssl/` but this new host has no such directory.  I have the following in my Hiera applied to all hosts:

```
tls_ca_certificate_file:    /etc/bacula/ssl/ca.pem
tls_certificate:            "/etc/bacula/ssl/%{trusted.certname}_cert.pem"
tls_dh_file:                '/etc/bacula/ssl/dh2048.pem'
tls_enable:                 true
tls_key:                    "/etc/bacula/ssl/%{trusted.certname}_key.pem"
tls_require:                true
tls_verify_peer:            true
```
I'm presently using the master branch here and digging through the code, I don't see anything to actually manage that directory or the certificates therein.  So I dug into the history and now see the rest of the ramifications of commit 8ce7049c0 where `Class[bacula:ssl]` got removed.

Do I just need to resurrect that code or something like it within my own?  I see something similar on the wiki for doing data storage encryption but for communications encryption.  I assume there's no special need to keep these private keys for communication offline like there would be for data storage, right?  I'd think in a recovery situation, a new client with new keys that could talk to the Bacula Dir & SD would be able to do a restore of its old-self -- provided there's no data storage encryption going on.

**Comment by jflorian** [comment]
Doh!  Never mind, I somehow didn't see all the rest of the TLS Setup wiki page.

**Comment by smortex** [comment]
Yeah, the two concepts are happily melted together with the Bacula naming of things :-)

* "TLS" in bacula wording refers to communication encryption.  It uses a PKI for the client and server to authenticate each other, and encrypts the communication, but what the storage daemon write to disk is the actual non-encrypted data.  ee [TLS Setup](https://github.com/xaque208/puppet-bacula/wiki/TLS-Setup).
* "PKI" in bacula wording refers to data encryption.  It use self-signed CA certificates and in no way is a Public Key Infrastructure. See [PKI Setup](https://github.com/xaque208/puppet-bacula/wiki/PKI-Setup).

You can configure none, one or both of these things :-)

I tried to explain how to configure this as simply as possible, but there is room for enhancement, so do not feel afraid of suggestion improvements!  Thanks!
