### ISSUE TITLE
Potential vulnerabilities in Puppet files: Hard-coded Secret

### ISSUE THREAD

**Issue by cantebigene** [xaque208/puppet-bacula#154]
3 hard-coded secrets were found in 3 different scripts.

Script 1: https://github.com/xaque208/puppet-bacula/blob/94a05d0780a90a4cc45cb85057b4b45bdfe87791/manifests/director.pp
 - Line [44](https://github.com/xaque208/puppet-bacula/blob/94a05d0780a90a4cc45cb85057b4b45bdfe87791/manifests/director.pp#L44): `db_user=bacula`

Script 2: https://github.com/xaque208/puppet-bacula/blob/94a05d0780a90a4cc45cb85057b4b45bdfe87791/manifests/client.pp
 - Line [68](https://github.com/xaque208/puppet-bacula/blob/94a05d0780a90a4cc45cb85057b4b45bdfe87791/manifests/client.pp#L68): `pki_encryption=and`

Script 3: https://github.com/xaque208/puppet-bacula/blob/94a05d0780a90a4cc45cb85057b4b45bdfe87791/manifests/director/postgresql.pp
 - Line [26](https://github.com/xaque208/puppet-bacula/blob/94a05d0780a90a4cc45cb85057b4b45bdfe87791/manifests/director/postgresql.pp#L26): `password=postgresql_password`

A secret can be a password, user name, or private cryptographic key. 

This type of smell can lead to well-known types of vulnerabilities, as documented by CWE ([CWE-798](https://cwe.mitre.org/data/definitions/798.html) and [CWE-259](https://cwe.mitre.org/data/definitions/259.html)). Hard-coded secrets can be used to bypass protection mechanisms, gain privileges on applications and access to sensitive data. 

Storing secrets in **Puppet** configuration files is considered to be a security smell (cf. [[icse19](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
To protect/manage your secrets, it is recommended to use a vault (e.g., [https://www.vaultproject.io/](https://www.vaultproject.io/)). After configuring the vault, you can replace your secrets by variables from the vault. For instance, replace`$password = ‘12345’` by `$password = $vault::password`. Thus, your secrets will no longer be disclosed publicly.

**Comment by smortex** [comment]
Meh :unamused:

Closing stupid :robot: issue that makes no sense at all…
