### ISSUE TITLE
Failed to apply catalog: Validation of Exec[generate_bacula_dhkey] failed: 'openssl dhparam -out dh1024.pem -5 1024' is not qualified and no path was specified.

### ISSUE THREAD

**Issue by peceka** [xaque208/puppet-bacula#39]
Hi,

after including your class (v1.2.5) and applying on client node i receive this error:
Failed to apply catalog: Validation of Exec[generate_bacula_dhkey] failed: 'openssl dhparam -out dh1024.pem -5 1024' is not qualified and no path was specified.

When i've changed:
modules/bacula/manifests/ssl.pp:68 to:
command => '/usr/bin/openssl dhparam -out dh1024.pem -5 1024',
It works.

**Comment by xaque208** [comment]
I've not run into this because I have an override in site.pp that looks like the following:
```Puppet
Exec {
  logoutput => 'on_failure',
  path      => '/usr/bin:/usr/sbin:/bin:/sbin',
}
```

You may wish to include something similar.
