### ISSUE TITLE
Include multiple storages?

### ISSUE THREAD

**Issue by e-it** [xaque208/puppet-bacula#60]
Hello,

I've got different servers in different datacentres. 

Now it would be the best to backup the content to storage-daemons that are located in the same datacenter (I don't have to pay for internal traffic).

Is it possible to define multiple storage-daemons and add clients according to their location?

**Comment by xaque208** [comment]
Yes, I do this too.  For each of the clients, set `bacula::params::storage` to the fqdn of the storage box.  I also set different pools for certain clients with `bacula::client::default_pool` so I can keep user retention settings different than server retention settings, etc.  Hope that helps.

**Comment by xaque208** [comment]
I hope you got this working for your environment.  Let me know if there are other questions here.
