### ISSUE TITLE
add and maintain a CHANGES file

### ISSUE THREAD

**Issue by fraenki** [xaque208/puppet-bacula#63]
...because it's hard to guess what's changed with every new release. :-)

**Comment by xaque208** [comment]
Point taken.  Its been in my head for a while, but I've honestly not been sure how to start.  I'll do a bit of reading this week and take a stab at putting something in place.  What version are you on currently?

**Comment by fraenki** [comment]
@xaque208 I've upgraded to 3.0.1 just today. Personally I like the style of the puppetlabs CHANGELOGs (i.e. https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/CHANGELOG.md).

**Comment by xaque208** [comment]
Hows this for a start? https://github.com/xaque208/puppet-bacula/pull/64

**Comment by xaque208** [comment]
Changelog has been merged.  Thank you for the suggestion.

**Comment by fraenki** [comment]
@xaque208 Great, thank you!
