### ISSUE TITLE
Unknown variable: 'bacula::client::packages'

### ISSUE THREAD

**Issue by jflorian** [xaque208/puppet-bacula#95]
I'm trying to upgrade from 4.1.0 to 5.0.0.  I've made all the documented changes concerning `bacula::params`, but am meeting this failure on my Fedora 25 host that serves as director, storage:

```Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Evaluation Error: Unknown variable: 'bacula::client::packages'. at /etc/puppetlabs/code/environments/bacula/modules/bacula/manifests/ssl.pp:52:24 on node scooby-f25.doubledog.org","issue_kind":"RUNTIME_ERROR","stacktrace":["Warning: The 'stacktrace' property is deprecated and will be removed in a future version of Puppet. For security reasons, stacktraces are not returned with Puppet HTTP Error responses."]}```

**Comment by jflorian** [comment]
This has me stumped.  Clearly `packages` is a parameter to `Class[bacula::client]` and `Class[bacula::client]` is included by `Class[bacula::ssl]` so I'm utterly at a loss as to what the problem is. I even tried restarting the Puppet Server because in the past I've seen the inexplicable suddenly corrected by such, but no such luck this time.

The only other oddity I see is in the puppetserver.log, which looks like something that needs to be corrected but not directly related here:

```2017-06-08 08:45:40,397 WARN  [qtp2022611857-404] [puppetserver] Puppet Module 'bacula': Value returned from data_hash function 'yaml_data', when using location '/etc/puppetlabs/code/environments/bacula/modules/bacula/data/os/RedHat.yaml', must use keys qualified with the name of the module
2017-06-08 08:45:40,433 WARN  [qtp2022611857-404] [puppetserver] Puppet Module 'bacula': Value returned from data_hash function 'yaml_data', when using location '/etc/puppetlabs/code/environments/bacula/modules/bacula/data/common.yaml', must use keys qualified with the name of the module
2017-06-08 08:45:40,434 WARN  [qtp2022611857-404] [puppetserver] Puppet Module 'bacula': Value returned from data_hash function 'yaml_data', when using location '/etc/puppetlabs/code/environments/bacula/modules/bacula/data/common.yaml', must use keys qualified with the name of the module
2017-06-08 08:45:40,434 WARN  [qtp2022611857-404] [puppetserver] Puppet Module 'bacula': Value returned from data_hash function 'yaml_data', when using location '/etc/puppetlabs/code/environments/bacula/modules/bacula/data/common.yaml', must use keys qualified with the name of the module
```

**Comment by xaque208** [comment]
Thank you for the report.  Would you mind sending a PR for the variable update in `common.yaml`?  Given that the error you are seeing is in the `ssl.pp` class, its entirely possible that this is related.  What version of Puppet are you running?

**Comment by jflorian** [comment]
I'll try to get a PR together, though it may not be soon for lack of time.  In the meantime, versions:

client => puppet-4.2.1-5.fc25.noarch
master => puppetserver-2.7.2-1.el7.noarch

**Comment by jflorian** [comment]
Please see PR #98.

I have no idea how to resolve the unknown variable error.

<rant>  This is a classic example of my love/hate relationship with Puppet.  I've never met another language that regularly presents so many confounding situations and it's probably not an exaggeration to say those number over a hundred.  It's always getting better, but it never seems to be good enough and the improvements always bring more pain and work. </rant>

**Comment by xaque208** [comment]
I can't test this at the moment, but it looks like this might be a simple change.

https://github.com/xaque208/puppet-bacula/blob/master/manifests/ssl.pp#L52

That may just need to read with the prefixed `$::`.
```puppet
require => Package[$::bacula::client::packages],
```

**Comment by xaque208** [comment]
@jflorian I'm happy to help answer any questions about puppet, though what you are pointing out here is likely just an oversight on my part.   So apologies for that.  This module has evolved quite a bit over the years to keep up with language patterns and such, so with lots of change comes potential for overlooking small details.

**Comment by jflorian** [comment]
I tried that (double colon prefix) and it did not help. 

On July 20, 2017 1:18:22 PM EDT, Zach Leslie <notifications@github.com> wrote:
>I can't test this at the moment, but it looks like this might be a
>simple change.
>
>https://github.com/xaque208/puppet-bacula/blob/master/manifests/ssl.pp#L52
>
>That may just need to read with the prefixed `$::`.
>```puppet
>require => Package[$::bacula::client::packages],
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/xaque208/puppet-bacula/issues/95#issuecomment-316771949

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xaque208** [comment]
I'll look in the evening to see if I'm seeing this sort of error.  Are you in a position to try puppet 4.4+?  I recall odd issues in early 4.x with regard to scope lookup.

**Comment by jflorian** [comment]
I took a stab at 5 yesterday but had to retreat until I can bring up a new VM. It quickly took on the feeling of a one way journey and couldn't risk going further "in place" for insufficient time. I'll check what I am currently running later (out of office ATM), but it is the latest from PC1 for EL7. 

On July 20, 2017 1:23:29 PM EDT, Zach Leslie <notifications@github.com> wrote:
>I'll look in the evening to see if I'm seeing this sort of error.  Are
>you in a position to try puppet 4.4+?  I recall odd issues in early 4.x
>with regard to scope lookup.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/xaque208/puppet-bacula/issues/95#issuecomment-316773246

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jflorian** [comment]
I am getting the error with puppet-4.6.2-4.fc26.noarch on the client and on the master:
puppetdb-terminus-3-1.el7.noarch
puppetdb-4.4.0-1.el7.noarch
puppetserver-2.7.2-1.el7.noarch
puppetdb-termini-4.4.0-1.el7.noarch
puppet-agent-1.10.4-1.el7.x86_64

So I'd say that 4.4+ doesn't help.  :-(  I am most curious to learn what you find.

**Comment by xaque208** [comment]
I'm also seeing this warning on my nodes, but it doesn't seem to have an impact.  I've started a branch that cleans up this (and other) warnings.

**Comment by xaque208** [comment]
All my nodes compile and apply cleanly.  I've been monitoring the puppet agent for quite some time, so if it had caused an issue with the node, I'd have known much earlier.

**Comment by jflorian** [comment]
Okay just to be clear, when you said "I'm also seeing this warning on my nodes", you were referring to the "unknown variable"? If so, I am really puzzled over the difference in behavior. I do have mine configured strictly with stringify_facts=false, future parser, etc. though I can't imagine those having an influence here. 

On July 21, 2017 11:04:18 AM EDT, Zach Leslie <notifications@github.com> wrote:
>All my nodes compile and apply cleanly.  I've been monitoring the
>puppet agent for quite some time, so if it had caused an issue with the
>node, I'd have known much earlier.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/xaque208/puppet-bacula/issues/95#issuecomment-317025562

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xaque208** [comment]
If I look for the keyword `bacula` in my `/var/log/puppetserver/puppetserver.log`, I see entries like the following.

```
2017-07-21 16:25:21,155 WARN  [qtp1497842208-39459] [puppetserver] Puppet Unknown variable: 'bacula::client::default_pool'. at /usr/local/etc/puppet/code/environments/production/modules/bacula/manifests/job.pp:56:31
2017-07-21 16:25:21,157 WARN  [qtp1497842208-39459] [puppetserver] Puppet Unknown variable: 'bacula::client::default_pool_full'. at /usr/local/etc/puppet/code/environments/production/modules/bacula/manifests/job.pp:57:31
2017-07-21 16:25:21,158 WARN  [qtp1497842208-39459] [puppetserver] Puppet Unknown variable: 'bacula::client::default_pool_inc'. at /usr/local/etc/puppet/code/environments/production/modules/bacula/manifests/job.pp:58:31
2017-07-21 16:25:21,160 WARN  [qtp1497842208-39459] [puppetserver] Puppet Unknown variable: 'bacula::client::default_pool_diff'. at /usr/local/etc/puppet/code/environments/production/modules/bacula/manifests/job.pp:59:31
2017-07-21 16:25:21,162 WARN  [qtp1497842208-39459] [puppetserver] Puppet Unknown variable: 'bacula::job_tag'. at /usr/local/etc/puppet/code/environments/production/modules/bacula/manifests/job.pp:72:31
2017-07-21 16:25:21,221 WARN  [qtp1497842208-39459] [puppetserver] Puppet Unknown variable: '::bacula::ssl::ssl_files'. at /usr/local/etc/puppet/code/environments/production/modules/bacula/manifests/client.pp:57:25
2017-07-21 16:25:21,222 WARN  [qtp1497842208-39459] [puppetserver] Puppet Arguments to Resource[] are all empty/undefined at /usr/local/etc/puppet/code/environments/production/modules/bacula/manifests/client.pp:57:25
```

This is in my branch that I worked on last night, so I don't see the missing packages variable anymore, but I'd like to fix those that remain before closing this out or merging to master.

**Comment by xaque208** [comment]
@jflorian In your manifests, are you including bacula::client before any jobs are declared?

**Comment by jflorian** [comment]
@xaque208 I do include `bacula::client` before any `bacula::job` declarations.  I do **not** have any ordering (i.e., `before`, `require`, etc.) between them though.

**Comment by xaque208** [comment]
@jflorian Give `5.1.0` a try and let me know if there is still an issue.  I am no longer seeing the warning in my logs.
